var theses = ['Studentische Hilfskräfte sollen ab sofort mit einem Mindestlohn von 8,50 € pro Stunde entlohnt werden.',
'Die Hochschulgruppen sollen ihre Finanzierung transparent machen müssen.',
'Die Erhöhung der Aufwandsentschädigung für die Tätigkeit im AStA von 175 € auf 200 € soll zurückgenommen werden.',
'Studierende, die im AStA arbeiten, sollen detailliert über ihre Arbeit Rechenschaft ablegen.',
'Das SP soll sich ausschließlich mit hochschulspezifischen Themen beschäftigen.',
'Das LesBiSchwulen- und trans*- Referat soll abgeschafft werden!',
'Die Studierendenschaft der Uni Bonn braucht kein Ökoreferat.',
'Nordbrückenpartys sollen vom SP öffentlich unterstützt werden.',
'Eine vom Verteidigungsministerium mitfinanzierte Henry-Kissinger-Professur für Völkerrecht und Internationale Beziehungen sollte nicht an der Uni Bonn eingerichtet werden.',
'Das Honors Program soll eingestellt werden.',
'In der Universität soll ein zentral gelegener Raum der Stille eingerichtet werden.',
'Der AStA soll sich verstärkt für die Einführung einer UniApp einsetzen.',
'Der AStA soll sich gegen die Zwangsexmatrikulation von Diplom/Magister/Staatsexamens-Studenten einsetzen.',
'Es soll eine Unicard eingeführt werden, die den Studierendenausweis, den ULB-Ausweis und eine Bezahlfunktion in Universität und Studentenwerk umfasst.',
'Ich halte die Mitgliedschaft im freien zusammenschluss von studentInnenschaften für sinnvoll.',
'Der AStA soll ein kritisches Gegengewicht zum offiziellen Lehrbetrieb sein und nicht nur konstruktiv mitarbeiten.',
'Die uneingeschränkte Freiheit der Forschung soll erhalten bleiben.',
'Die Mensa soll in Zukunft keine Empfehlung für einen "fleischfreien Donnerstag" (Veggieday) mehr abgeben.',
'Die IT-Infrastruktur sollte eine höhere Priorität genießen.',
'Leistungsnachweise im Studium sollten pseudonymisiert werden.',
'Der AStA soll eine feste Vermittlungsstelle für "Wohnen für Hilfe" einrichten.',
'Das Studierendenparlament soll sich auf kommunaler Ebene für den Ausbau der Fahrradwege in Bonn einsetzen.',
'Die Studierenden sollten uneingeschränkt über die weitere Nutzung ihrer akademischen Erzeugnisse bestimmen können.'];

var theses_short = ['SHK-Mindestlohn',
'HSG-Finanzierung',
'Aufwandsentschädigungen',
'AStA-Rechenschaft',
'hochschulpolitisches Mandat',
'LBST-Referat',
'Ökoreferat',
'Nordbrückenpartys',
'Henry-Kissinger-Professur',
'Honors Program',
'Raum der Stille',
'UniApp',
'Zwangsexmatrikulation',
'Unicard',
'fzs',
'AStA als Gegengewicht',
'Freiheit der Forschung',
'Veggieday',
'IT-Infrastruktur',
'Pseudonymisierung',
'Wohnen für Hilfe',
'Fahrradwege',
'Nutzungsrechte'];

var explanations =['',
'',
'',
'',
'',
'Das LesBiSchwulen- und trans*-Referat als Anlaufstelle für homo-, bi- und transsexuelle Studierende bietet persönliche Beratung und Betreuung und organisiert regelmäßig Veranstaltungen.',
'Das Referat für Ökologie setzt sich für Umweltschutz und Nachhaltigkeit an der Universität ein, und zwar konkret (nach eigenen Angaben) für mehr Energie- und Ressourceneffizienz, Müllvermeidung und Recycling, Förderung umweltschonender Mobilität und nachhaltigen Konsum.',
'Die Partys an der Nordbrücke sind autonom organisierte Freiluftpartys, die nicht offiziell angemeldet werden und daher nicht legal sind.',
'Die Stiftungsprofessur, die vom Außen- und vom Verteidigungsministerium für fünf Jahre finanziert wird, wird vom AStA und Teilen des SP kritisiert, weil dem Namensgeber Henry Kissinger Verwicklungen in völkerrechtswidrige Militäraktionen vorgeworfen werden und eine inhaltliche Beeinflussung der Lehre durch das Verteidigungsministerium befürchtet wird.',
'Das Honors Program der Universität soll 150 besonders begabte Bachelorstudierende pro Jahrgang durch interdisziplinäre Veranstaltungen fördern. Die Finanzmittel dafür werden aus den Instituten genommen, deren ProfessorInnen Vorlesungen und Seminare für das Honors Program anbieten. Zulassungskriterium für das Program ist ind er Regel der Notenschnitt im ersten Bachelorjahr.',
'',
'An vielen Universitäten werden bereits Apps für Smartphones angeboten, die Informationen wie z.B. das Mensaangebot, News, entfallende Veranstaltungen und die Unimails beinhalten.',
'Aufgrund der Umstellung auf das Bachelor- und Mastersystem werden Studierende, die noch immer in auslaufenden Diplom- und Magisterstudiengängen eingeschrieben sind, inzwischen teilweise zwangsexmatrikuliert.',
'',
'Der freie zusammenschluss von studentInnenschaften (fzs) e.V. ist der überparteiliche Dachverband von Studierendenvertretungen in Deutschland. Der Mitgliedsbeitrag richtet sich nach der Zahl der eingeschrieben Studierenden. 2012/13 zahlte die Verfasste Studierendenschaft der Uni Bonn 24.293,60 € an den fzs, im aktuellen Nachtragshaushaltsplan sind 26.000 € dafür vorgesehen.',
'',
'Die uneingeschränkte Freiheit der Forschung zählt zu den bürgerlichen Grundrechten. In Deutschland wird die Freiheit der Wissenschaft, Forschung und Lehre gemäß Artikel 5 des Grundgesetzes als Grundrecht geschützt. Dieses Grundrecht gerät an seine Grenzen, wenn andere Verfassungswerte dadurch betroffen sind (z.B. Gentechnik, Embryonenforschung, Militärforschung).',
'',
'',
'Alle Leistungen (Klausuren, Hausarbeiten etc.) sollen pseudonymisiert bewertet werden. Das heißt, die Dozenten sollen ohne Kenntnis des Urhebers die Leistung beurteilen.',
'Die Grundidee des Projekts "Wohnen für Hilfe", das in einigen Universitätsstädten bereits existiert, ist die Vermittlung von Studierenden an Senioren, Familien, Alleinerziehende, Menschen mit Behinderung, die Wohnraum zur Verfügung stellen. Im Gegenzug unterstützen die Studierenden den Wohnraumanbieter bei der Verrichtung alltäglicher Aufgaben. Mit dem Ziel der Etablierung dieses Projekts in Bonn, soll eine Vermittlungsstelle diese beiden Parteien zusammenbringen und betreuen.',
'',
'Die Hochschule hat einen rechtlichen Anspruch auf das erste Original der Abschlussarbeit. Zudem kann der Studierende Nutzungs-, Veröffentlichungs- und Vervielfältigungsrechte an Dritte abtreten.'];